### ISSUE TITLE
[Code review] Inconsistency in the way emails are built

### ISSUE THREAD

**Issue by davidbgk** [prswb/prswb#3]
In uxperiment/utils.py, there are different ways to build emails (from a dict for content, with ifs for titles, with ifs for title+content in build_admin_email).

There are many ways to achieve that but the most important is to be consistent, I propose to create a dict of tuples with {"type": (subject, content)} to use in all cases.

**Comment by vinyll** [comment]
email subjects are in tuples, bodies are in templates.
