### ISSUE TITLE
[Code review] Never silently pass unqualified errors

### ISSUE THREAD

**Issue by davidbgk** [prswb/prswb#9]
In prswb/pages/views.py:

```
    except:
        pass
```

means whatever happen in this block, even related to your code will just pass silently, this is a nightmare for maintenability. Always find which errors can be raised or wait for those to happen but do not pass.

Bonus: try to restrict the try/except to one line of code, not a block.

**Comment by n1k0** [comment]
fixed by 77c5c0959629118adb6939181271741d82ad2479
